version: '0'
services:
  myservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: $IMAGE_URI
    entrypoint: /bin/bash
    working_dir: /home/
    tty: true
    stdin_open: true
    volumes:
      - $DIR_LOC:$DIR_REM
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
